# general settings
name: OURNet2404-2024-01-23-LOLv1
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10



datasets:
  train:
    name: LOLdataset_v1
    type: PairedImageDataset  #配对数据集
    dataroot_gt: /home/wen/data_3/XianYu/2024_04/NAFNet-main/datasets/LOLdataset_v1/our485_1/high
    dataroot_lq: /home/wen/data_3/XianYu/2024_04/NAFNet-main/datasets/LOLdataset_v1/our485_1/low
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: LOL_eval15
    type: PairedImageDataset
    dataroot_gt: /home/wen/data_3/XianYu/2024_04/NAFNet-main/datasets/LOLdataset_v1/eval15/high
    dataroot_lq: /home/wen/data_3/XianYu/2024_04/NAFNet-main/datasets/LOLdataset_v1/eval15/low
    io_backend:
      type: disk



network_g:
  type: OURNet2404  # 我们的模型
  width: 48
  enc_blk_nums: [2, 2, 4, 8]
  middle_blk_num: 12
  dec_blk_nums: [2, 2, 2, 2]

# path
path:
  pretrain_network_g: ~ # experiments/WaterNet-2024-01-07/models/net_g_44000.pth
  strict_load_g: true
  resume_state: ~
#  resume_state: auto  # 这里加上auto之后会接续断点进行训练

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 100000  # 500000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500




# 训练命令：python basicsr/train.py  -opt options/train/Water/train2405_LOLv1.yml

# 单卡训练防止分布式的验证：python -m torch.distributed.launch --nproc_per_node=1 --master_port=4321 basicsr/train.py -opt options/train/OURNet/train2405_LOLv1.yml --launcher pytorch



